name: dbt_tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
env:
  DBT_PROJECT_NAME: "bikestores"
  DBT_CURATED_MODEL: "curated_db"
  DBT_ANALYTICS_MODEL: "analytics_db"
  BIKESTORES_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  BIKESTORES_DBT_USER: ${{ secrets.SNOWFLAKE_USER }}
  BIKESTORES_DBT_PASS: ${{ secrets.SNOWFLAKE_PASS }}
  BIKESTORES_DBT_SVC: ${{ secrets.SNOWFLAKE_ROLE }}
  BIKESTORES_DB: "bikestores_curated_db"
  BIKESTORES_WH: "bikestores_developer_wh"
  BIKESTORES_SCHEMA: "edm"

jobs:
  dbt:
    name: test_base_tbl_zero_row_counts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"
      - run: pip3 install --upgrade dbt
      - run: dbt --version
      - run: cd bin/dbt/${DBT_PROJECT_NAME} && dbt debug --profiles-dir profiles
      - run: cd bin/dbt/${DBT_PROJECT_NAME} && dbt test --profiles-dir profiles --models ${DBT_CURATED_MODEL}
      - run: cd bin/dbt/${DBT_PROJECT_NAME} && dbt run --profiles-dir profiles --models ${DBT_CURATED_MODEL}
